apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        secret-checksum: {{ include (print $.Template.BasePath "/quicksight-secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: quicksight-sa
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.spec.containers.image }}"
          env:
            - name: AWS_ACCOUNT_ID
              value: {{ .Values.env.awsAccountId | quote }}
            - name: DB_INSTANCE_ID
              value: "{{ .Values.env.dbInstanceId }}"
            - name: DB_USER
              value: "{{ .Values.env.dbUser }}"
            - name: DB_NAME
              value: "{{ .Values.env.dbName }}"
            - name: TECH_DEBT_DATA_SET_ID
              value: "{{ .Values.env.techDebtDataSetId }}"
            - name: TECH_DEBT_DATA_SET_NAME
              value: "{{ .Values.env.techDebtDataSetName }}"
            - name: DASHBOARD_ID
              value: "{{ .Values.env.dashboardId }}"
            - name: DASHBOARD_NAME
              value: "{{ .Values.env.dashboardName }}"
            - name: REGION
              value: "{{ .Values.env.region }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: {{ .Values.name }}-secret
