apiVersion: v1
kind: ServiceAccount
metadata:
  name: quicksight-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::358354085340:role/eksctl-appmod-foresight-nodegroup-NodeInstanceRole-1H28PSCPWYCOY
