apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  gituser: {{ .Values.secret.data.gituser }}
  gitpassword: {{ .Values.secret.data.gitpassword }}
