{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ quote .Values.istio.hosts }}
  gateways:
  - {{ .Values.istio.gateways }}
  http:
  - timeout: 60s
    route:
    - destination:
        host: {{ .Values.name }}
        port:
          number: {{ .Values.istio.port }}
{{- end }}
