apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  gitpassword: {{  .Values.secret.git_password  }}
  postgres_password: {{ .Values.secret.postgres_password }}
