apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.spec.volumes.persistentVolumeClaim }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.spec.volumes.persistentVolumeClaimStorage }}
  storageClassName: {{ .Values.spec.volumes.storageClass }}
