apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
      - name: {{ .Values.name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.spec.volumes.persistentVolumeClaim }}
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{ end }}
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: {{ .Values.spec.containers.imagePullPolicy }}
        image: {{ .Values.spec.containers.image }}
        args: ["--app.cors.allowed-origins[0]={{ .Values.keycloak.allowed_origins }}",
        "--app.cors.allowed-origins[1]=http://localhost:4200",
        "--keycloak.enabled=true",
        "--keycloak.auth-server-url={{ .Values.keycloak.auth_server_url }}",
        "--keycloak.ssl-required=none",
        "--keycloak.realm={{ .Values.keycloak.realm }}",
        "--keycloak.resource={{ .Values.keycloak.resource }}",
        "--keycloak.bearer-only=true",
        "--keycloak.autodetect-bearer-only=true",
        "--keycloak.enable-basic-auth=false",
        "--keycloak.use-resource-role-mappings=false",
        "--keycloak.public-client=true",
        "--keycloak.principal-attribute=preferred_username"]
        volumeMounts:
        - name: {{ .Values.name }}-persistent-storage
          mountPath: /AMaaS/advisor-reports
        env:
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: gitpassword
              name: {{ .Values.name }}-secret
        - name: DATABASE_USERNAME
          value: {{ .Values.env.database_username }}
        - name: DATABASE_URL
          value: {{ .Values.env.database_url }}
        - name: DATABASE_NAME
          value: {{ .Values.env.database_name }}
        - name: DATABASE_SCHEMA
          value: {{ .Values.env.database_schema }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres_password
              name: {{ .Values.name }}-secret
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config
        ports:
        - containerPort: {{ .Values.spec.containers.ports.containerPort }}
        resources:
          limits:
            cpu: "1000m"
            memory: "2048Mi"
          requests:
            cpu: "125m"
            memory: "1024Mi"
