apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        configmap-checksum: {{ include (print $.Template.BasePath "/reportservice-config.yaml") . | sha256sum }}
        secret-checksum: {{ include (print $.Template.BasePath "/reportservice-secret.yaml") . | sha256sum }}
    spec:
      volumes:
      - name: {{ .Values.name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.spec.volumes.persistentVolumeClaim }}
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{ end }}
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: {{ .Values.spec.containers.imagePullPolicy }}
        image: {{ .Values.spec.containers.image }}
        args: ["--app.cors.allowed-origins[0]={{ .Values.container.args.keycloak.app_cors_allowed_origins }}",
        "--app.cors.allowed-origins[1]={{ .Values.container.args.keycloak.app_cors_allowed_origins_1 }}",
        "--app.cors.allowed-origins[2]={{ .Values.container.args.keycloak.app_cors_allowed_origins_2 }}",
        "--app.cors.allowed-origins[3]={{ .Values.container.args.keycloak.app_cors_allowed_origins_3 }}",
        "--keycloak.enabled={{ .Values.container.args.keycloak.keycloak_enabled }}",
        "--keycloak.auth-server-url={{ .Values.container.args.keycloak.keycloak_auth_server_url }}",
        "--keycloak.ssl-required={{ .Values.container.args.keycloak.keycloak_ssl_required }}",
        "--keycloak.realm={{ .Values.container.args.keycloak.keycloak_realm }}",
        "--keycloak.resource={{ .Values.container.args.keycloak.keycloak_resource }}",
        "--keycloak.bearer-only={{ .Values.container.args.keycloak.keycloak_bearer_only }}",
        "--keycloak.autodetect-bearer-only={{ .Values.container.args.keycloak.keycloak_autodetect_bearer_only }}",
        "--keycloak.enable-basic-auth={{ .Values.container.args.keycloak.keycloak_enable_basic_auth }}",
        "--keycloak.use-resource-role-mappings={{ .Values.container.args.keycloak.keycloak_use_resource_role_mappings }}",
        "--keycloak.public-client={{ .Values.container.args.keycloak.keycloak_public_client }}",
        "--keycloak.principal-attribute={{ .Values.container.args.keycloak.keycloak_principal_attribute }}"]
        volumeMounts:
        - name: {{ .Values.name }}-persistent-storage
          mountPath: /AMaaS/advisor-reports
        env:
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: gitpassword
              name: {{ .Values.name }}-secret
        - name: DATABASE_USERNAME
          value: {{ .Values.env.database_username }}
        - name: DATABASE_URL
          value: {{ .Values.env.database_url }}
        - name: DATABASE_NAME
          value: {{ .Values.env.database_name }}
        - name: DATABASE_SCHEMA
          value: {{ .Values.env.database_schema }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres_password
              name: {{ .Values.name }}-secret
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config
        ports:
        - containerPort: {{ .Values.spec.containers.ports.containerPort }}
        resources:
          limits:
            cpu: "1000m"
            memory: "2048Mi"
          requests:
            cpu: "125m"
            memory: "1024Mi"
