apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.ingress.port }}
    targetPort: {{ .Values.spec.containers.ports.containerPort }}
    name: http
  selector:
    app: {{ .Values.name }}
