apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  keycloak_master_password: {{ .Values.container.args.keycloak.keycloak_master_password }}
  password: {{ .Values.database_password }}
