apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name:  {{ .Values.name }}
  labels:
    app:  {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.name }}
    spec:
      imagePullSecrets:
        - name:  {{ .Values.imagePullSecrets.name }}
      containers:
      - name:  {{ .Values.name }}
        image: {{ .Values.container.image.repository }}
        imagePullPolicy: {{ .Values.container.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        args: ["--app.cors.allowed-origins[0]={{ .Values.container.args.keycloak.app_cors_allowed_origins }}",
          "--app.cors.allowed-origins[1]={{ .Values.container.args.keycloak.app_cors_allowed_origins_1 }}",
          "--app.cors.allowed-origins[2]={{ .Values.container.args.keycloak.app_cors_allowed_origins_2 }}",
          "--app.cors.allowed-origins[3]={{ .Values.container.args.keycloak.app_cors_allowed_origins_3 }}",
          "--keycloak.enabled={{ .Values.container.args.keycloak.keycloak_enabled }}",
          "--keycloak.auth-server-url={{ .Values.container.args.keycloak.keycloak_auth_server_url }}",
          "--keycloak.ssl-required={{ .Values.container.args.keycloak.keycloak_ssl_required }}",
          "--keycloak.realm={{ .Values.container.args.keycloak.keycloak_realm }}",
          "--keycloak.resource={{ .Values.container.args.keycloak.keycloak_resource }}",
          "--keycloak.bearer-only={{ .Values.container.args.keycloak.keycloak_bearer_only }}",
          "--keycloak.autodetect-bearer-only={{ .Values.container.args.keycloak.keycloak_autodetect_bearer_only }}",
          "--keycloak.enable-basic-auth={{ .Values.container.args.keycloak.keycloak_enable_basic_auth }}",
          "--keycloak.use-resource-role-mappings={{ .Values.container.args.keycloak.keycloak_use_resource_role_mappings }}",
          "--keycloak.public-client={{ .Values.container.args.keycloak.keycloak_public_client }}",
          "--keycloak.principal-attribute={{ .Values.container.args.keycloak.keycloak_principal_attribute }}"]
        env:
            - name: DATABASE_USERNAME
              value: {{ .Values.database_username }}
            - name: DATABASE_URL
              value: {{ .Values.database_url }}
            - name: DATABASE_NAME
              value: {{ .Values.database_name }}
            - name: REDIS_HOST
              value: {{ .Values.redis_host }}
            - name: KEYCLOAKADMIN_MASTER_USERNAME
              value: {{ .Values.container.args.keycloak.keycloak_master_username }}
            - name: KEYCLOAKADMIN_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keycloak_master_password
                  name: {{ .Values.name }}-secrets
            - name: KEYCLOAKADMIN_KEYCLOAK_URL
              value: {{ .Values.container.args.keycloak.keycloak_auth_server_url }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.name }}-secrets
