apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.container.port }}
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
