# Default values for SCC-Agent.
# This is a YAML-formatted file.

name: scc
namespace:
replicas: 1

imagePullSecret:
  name:
container:
  name:
  imagePullPolicy:
  image:
  containerPort: 8080

secret:
  git_password:

env:
  keycloak:
    keycloak_allowed_origins_1:
    keycloak_auth_server_url:
    keycloak_resource:
    keycloak_realm:
  foresight_backend_url:
  git:
    git_cli_protocol:
    git_server_url:
    git_local_dir:
    git_user:
  spring_kafka_bootstrap_servers: ""
  
volumes:
  name:
  persistentVolumeClaim:

ingress:
  enabled: true
  hosts:
    - sample.com
  # The ingress path. Useful to host metabase on a subpath, such as `/metabase`.
  path: /
  labels:
    # Used to add custom labels to the Ingress
    # Useful if for example you have multiple Ingress controllers and want your Ingress controllers to bind to specific Ingresses
    # traffic: internal
  annotations: {}
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  tls:
    - secretName: tls-sample.com
      hosts:
        - sample.com

istio:
  hosts: ""
  gateways: istio-ingress/istio-autogenerated-k8s-ingress
  port: 8080
  enabled: false