apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{ end }}
      containers:
      - name: {{ .Values.container.name }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        image: {{ .Values.container.image }}
        args: ["--app.cors.allowed-origins[0]={{ .Values.container.args.keycloak.app_cors_allowed_origins }}",
        "--app.cors.allowed-origins[1]={{ .Values.container.args.keycloak.app_cors_allowed_origins_1 }}",
        "--app.cors.allowed-origins[2]={{ .Values.container.args.keycloak.app_cors_allowed_origins_2 }}",
        "--app.cors.allowed-origins[3]={{ .Values.container.args.keycloak.app_cors_allowed_origins_3 }}",
        "--keycloak.enabled={{ .Values.container.args.keycloak.keycloak_enabled }}",
        "--keycloak.auth-server-url={{ .Values.container.args.keycloak.keycloak_auth_server_url }}",
        "--keycloak.ssl-required={{ .Values.container.args.keycloak.keycloak_ssl_required }}",
        "--keycloak.realm={{ .Values.container.args.keycloak.keycloak_realm }}",
        "--keycloak.resource={{ .Values.container.args.keycloak.keycloak_resource }}",
        "--keycloak.bearer-only={{ .Values.container.args.keycloak.keycloak_bearer_only }}",
        "--keycloak.autodetect-bearer-only={{ .Values.container.args.keycloak.keycloak_autodetect_bearer_only }}",
        "--keycloak.enable-basic-auth={{ .Values.container.args.keycloak.keycloak_enable_basic_auth }}",
        "--keycloak.use-resource-role-mappings={{ .Values.container.args.keycloak.keycloak_use_resource_role_mappings }}",
        "--keycloak.public-client={{ .Values.container.args.keycloak.keycloak_public_client }}",
        "--keycloak.principal-attribute={{ .Values.container.args.keycloak.keycloak_principal_attribute }}"]
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config
          - secretRef:
              name: {{ .Values.name }}-secret
        ports:
        - containerPort: {{ .Values.container.containerPort }}
