apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  FORESIGHT_BACKEND_URL: {{ .Values.env.foresight_backend_url | quote }}
  GIT_CLI_PROTOCOL: {{ .Values.env.git.git_cli_protocol | quote }}
  GIT_SERVER_URL: {{ .Values.env.git.git_server_url | quote }}
  GIT_LOCAL_DIR: {{ .Values.env.git.git_local_dir | quote }}
  GIT_USER: {{ .Values.env.git.git_user | quote }}
  GIT_GROUP: {{ .Values.env.git.git_group | quote }}
  KEYCLOAK_REALM: {{ .Values.env.keycloak.keycloak_realm | quote }}
  KEYCLOAK_AUTH_SERVER_URL: {{ .Values.env.keycloak.keycloak_auth_server_url | quote }}
  KEYCLOAK_RESOURCE: {{ .Values.env.keycloak.keycloak_resource | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.spring_kafka_bootstrap_servers | quote }}
  DATABASE_USERNAME: {{ .Values.env.database_username | quote }}
  DATABASE_URL: {{ .Values.env.database_url | quote }}
  DATABASE_NAME: {{ .Values.env.database_name | quote }}
  DATABASE_SCHEMA: {{ .Values.env.database_schema | quote }}

