apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.server.secret.username }}
  password: {{ .Values.server.secret.password }}
