{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    name: {{ .Values.namespace.name }}
  name: {{ .Values.namespace.name }}
{{- end }}
