apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.name }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  username: {{ .Values.server.secret.username }}
  password: {{ .Values.server.secret.password }}
  additionalAccountPassword: {{ .Values.server.secret.additionalAccountPassword }} #For setting Viewer and Manager Password
