apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.env.database_persistentVolumeClaim }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.env.database_persistentVolumeClaimStorage }}
  storageClassName: {{ .Values.env.database_storageClassName }}
