apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  awsAccessKey: {{ .Values.cloud_aws.credentials.accessKey }}
  awsSecretKey: {{ .Values.cloud_aws.credentials.secretKey }}
  keycloakadminuser: {{ .Values.secret.keycloakadminuser }}
  keycloakadminpassword: {{ .Values.secret.keycloakadminpassword }}
  metabasesecretkey: {{ .Values.secret.metabasesecretkey }}
  highlighttokenusername: {{ .Values.secret.highlighttokenusername }}
  highlighttokenpassword: {{ .Values.secret.highlighttokenpassword }}
  sage_machinelearning_client_password: {{ .Values.secret.sage_machinelearning_client_password }}
  postgres_password: {{ .Values.secret.postgres_password }}
