apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "metabase.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  admin_user: {{ .Values.admin.username }}
  admin_password: {{ .Values.admin.password }}
