{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "metabase.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.virtualservice.host }}
  gateways:
  - {{ .Values.virtualservice.gateways }}
  http:
    - route:
        - destination:
            host: {{ template "metabase.fullname" . }}
            port:
              number: {{ .Values.virtualservice.port }}
{{- end -}}
