{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ quote .Values.ingress.hosts }}
  gateways:
  - {{ .Values.ingress.gateways }}
  http:
    - route:
        - destination:
            host: {{ .Values.name }}
            port:
              number: {{ .Values.ingress.port }}
{{- end }}
