# Default values for Sage-ML.
# This is a YAML-formatted file.

name: sage-ml
namespace: sage
replicas: 1

image:
  repository:
  imagePullSecrets:
containers:
  name:
  imagePullPolicy:
  image:
  port: 5000

secret:
  data:
    keycloak_client_secret:
    flask_app_secret_key:

keycloak:
  auth_server_url:
  realm:
  client_id:

ingress:
  enabled: true
  hosts:
    - sample.com
  # The ingress path. Useful to host metabase on a subpath, such as `/metabase`.
  path: /
  labels:
    # Used to add custom labels to the Ingress
    # Useful if for example you have multiple Ingress controllers and want your Ingress controllers to bind to specific Ingresses
    # traffic: internal
  annotations: {}
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  tls:
    - secretName: tls-sample.com
      hosts:
        - sample.com

istio:
  hosts: ""
  gateways:
  port: 5000
  enabled: true
