{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.istio.hosts }}
  gateways:
  - {{ .Values.istio.gateways }}
  http:
    - route:
      - destination:
            host: {{ .Values.name }}
            port:
              number: {{ .Values.istio.port }}
{{- end }}
