apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secret.data.keycloak_client_secret }}
  FLASK_APP_SECRET_KEY: {{ .Values.secret.data.flask_app_secret_key }}
