replicas: 1
name: quicksight
namespace: quicksight

spec:
  containers:
    imagePullPolicy: Always
    image: quicksight
    ports:
      containerPort: 8089
env:
  awsAccountId: "358354085340"
  dbInstanceId: "appmodforesightdev-0"
  dbUser: "foresight"
  dbName: "quicksight"
  dataSetId: ""
  dataSetName: ""
  dashboardId: ""
  dashboardName: ""
  physicalTableMap: ""
  sourceEntity: ""
  region: "us-east-1"
secret:
  db_password: ""

## Edit this to match your keycloak
client_secret: |
  {
    "web": {
          "issuer": "https://keycloak-dev.c1d.saicappmod.com/auth/realms/TCloud",
          "auth_uri": "https://keycloak-dev.c1d.saicappmod.com/auth/realms/TCloud/protocol/openid-connect/auth",
          "client_id": "superset",
          "client_secret": "",
          "redirect_urls": [
              "http://localhost:8088/*"
          ],
          "userinfo_uri": "https://keycloak-dev.c1d.saicappmod.com/auth/realms/TCloud/protocol/openid-connect/userinfo",
          "token_uri": "https://keycloak-dev.c1d.saicappmod.com/auth/realms/TCloud/protocol/openid-connect/token",
          "token_introspection_uri": "https://keycloak-dev.c1d.saicappmod.com/auth/realms/TCloud/protocol/openid-connect/token/introspect"
      }
  }
